#!/bin/bash
# Run scripts to validate application
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[[ "${VERBOSE:-0}" =~ ^[0-9]+$ ]] && VERBOSE="${VERBOSE:-0}" || VERBOSE=1
export VERBOSE

ORANGE='\033[38;5;208m'
NC='\033[0m'

[[ "$VERBOSE" -ne 0 ]] && echo -e "${ORANGE}scripts/tests${NC}"
"$SCRIPT_DIR/tests"

[[ "$VERBOSE" -ne 0 ]] && echo

[[ "$VERBOSE" -ne 0 ]] && echo -e "${ORANGE}tests/validate${NC}"
"$SCRIPT_DIR/../tests/validate"
