#!/usr/bin/env bash
# Create/use a worktree for a feature branch
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR

# Only works for git repos
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "ERROR: not in a git repository"
    exit 1
fi

# Check arguments
if [[ $# != 1 ]]; then
    echo "Usage: worktree FEATURE-BRANCH-NAME"
    exit 0
fi
FEATURE="$1"

# Run this from the root repo, not a worktree
COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
PROJECT_DIR="$(realpath "$COMMON_DIR/..")"
FEATURE_DIR="$PROJECT_DIR/worktrees/$FEATURE"

# Create the git worktree and branch
mkdir -p "$FEATURE_DIR"
if [[ ! -f "$FEATURE_DIR/.git" ]]; then
    git worktree add "$FEATURE_DIR" -b "$FEATURE"
    pushd "$FEATURE_DIR" >/dev/null
    direnv allow
    popd >/dev/null
fi

SHORTDIR="$(realpath --relative-to "$(pwd)" "$FEATURE_DIR")"
echo "Worktree created in '$SHORTDIR'"
